// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Movido por Números",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Movido por Números",
            targets: ["AppModule"],
            bundleIdentifier: "com.luanagerber.Movido-por-Nu-meros-v2-0",
            teamIdentifier: "UZ6BDJX457",
            displayVersion: "3.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: "public.app-category.books"
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)